### ISSUE TITLE
[macos] onTrayMenuItemClick not activated in master any more.

### ISSUE THREAD

**Issue by jeanantoine** [leanflutter/tray_manager#10]
Hello,

on macos in the example when using the package from pub:
`tray_manager: ^0.1.3`

```
void onTrayMenuItemClick(MenuItem menuItem) {
    print(menuItem.toJson());
    BotToast.showText(
      text: '${menuItem.toJson()}',
    );
  }
```

`onTrayMenuItemClick` is activated when I select a menu item.

When I use tray_manager from the master 

  ```
tray_manager:
    path: ../
```

 the example does not work any more.

I use the master because of [issue 4](https://github.com/leanflutter/tray_manager/issues/4)

**Comment by lijy91** [comment]
Fixed.
