### ISSUE TITLE
plz provide a method that when call popUpContextMenu don`t bring the window into the foreground .

### ISSUE THREAD

**Issue by lemos1235** [leanflutter/tray_manager#23]
please provide a method that when call `popUpContextMenu ` don`t bring the window into the foreground .

**Comment by Qrnbth** [comment]
additionally,calling popUpContextMenu would also call window to get focused,
which is unexpectedly caused a blank screen if none of the widgets needs to rerender after window re-show,
coop with window_manager

**Comment by EthanBarlow** [comment]
This issue was opened over 2 years ago so this is more for documentation purposes, but there is a PR now. #58
