### ISSUE TITLE
Is there a way to hide the Tray Icon

### ISSUE THREAD

**Issue by gaddlord** [leanflutter/tray_manager#29]
I would like to show the Tray Icon only when I minimize the app (I use Window_Manager package to that) and hide the Tray Icon after double-clicking over it.

Can this be ahieved?

**Comment by lijy91** [comment]
You just need to call the `destroy` method.

**Comment by gaddlord** [comment]
I don't believe this solves my problem. I do call trayManager.destroy() on disposal. But I want to show/hide the tray icon multiple times during the application lifecycle.
I believe it will be nice to have isVisible and setVisible which toggle visibility by calling Shell_NotifyIcon():

  NIM_ADD         = $00000000;
  NIM_DELETE      = $00000002;
