### ISSUE TITLE
Support setTitle for macOS

### ISSUE THREAD

**Issue by andynvt** [leanflutter/tray_manager#32]
Please support setTitle like this package: https://pub.dev/packages/system_tray. Thank you so much

![CleanShot 2023-03-08 at 11 02 18](https://user-images.githubusercontent.com/26719596/223616607-3394eeea-0827-43b5-b784-ad4d3e5edd74.png)

**Comment by lijy91** [comment]
It supports setTitle, Please run the sample project.

![image](https://user-images.githubusercontent.com/3889523/223617450-79189aec-6d2b-44d5-94be-9f643b7fdea7.png)
