### ISSUE TITLE
i want to custom menu windows

### ISSUE THREAD

**Issue by szxv587** [leanflutter/tray_manager#33]
Having the position of the icon would allow for custom menu windows to be displayed like so:
<img width="686" alt="67123957-d7b6bb00-f1f1-11e9-8de8-b4931bf9b580" src="https://user-images.githubusercontent.com/18606623/231634464-d3ac6bca-677d-41cd-a0e4-0bc098c56d4e.png">

**Comment by lijy91** [comment]
This requires change NSWindow to NSPopover, as you can see in this example https://github.com/wolfenrain/flutter_in_status_bar

**Comment by hpelitebook745G2** [comment]
@lijy91 do you get this error as well?
```
flutter_in_status_bar/macos/Runner/AppDelegate.swift:16:25: error: value of optional type 'NSWindow?' must be unwrapped to refer to member 'contentView' of wrapped base type 'NSWindow'
```
