### ISSUE TITLE
Windows icon not showing

### ISSUE THREAD

**Issue by KoVaL05** [leanflutter/tray_manager#49]
Hello, I am having issues with setting icons on Windows. I tried many combinations and images, but nothing worked. Do you have any idea what the issue may be?

Here's the code:
    await trayManager.setIcon(GetPlatform.isWindows
? 'assets/images/logo_icon.ico'
: 'assets/images/logo_icon.png');

And here's the pubspec.yaml:
  assets:
- assets/images/
- assets/logo/

**Comment by Asmitta-01** [comment]
I have the same issue: 
```dart
await trayManager.setIcon(ImageData.windowsBasedIcon);
// And windowsBasedIcon = 'assets/images/icons/app-icon.ico'
```
